config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles
  # get 'articles', to: 'articles#index'
  # get 'articles/:id', to: 'articles#show'

  # Routes for User actions
  get 'signup', to: 'users#new'

  # The form_with statement in users/_form.html.erb needs to know where to post
  # the form.  Since we pass it model: @user, it looks for users_path.
  # Since the form is invoked by the "new" method we complete the new user creation
  # by sending the form's data to the create method:
  # post 'users', to: 'users#create'
  # Alternatively, the resources statement assigns all the standard routes.  But we
  # want the "new" method to be invoked by signup [as above] so we can omit it from the
  # resources statement
  resources :users, except: [:new]

  # Routes for Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  # Tried "delete 'Logout', to 'sessions#destry" but that didn't work
  get 'logout', to: 'sessions#destroy'

  #  Routes for Categories
  resources :categories
end

app/models/category.rb
# frozen_string_literal: true

# Class to model Category(s) of Articles of Alpha Blog 2
class Category < ApplicationRecord
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { minimum: 3, maximum: 20 }

  # Associations
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# Class for article Categories controller
class CategoriesController < ApplicationController
  before_action :require_admin_user, except: %i[index show]
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5).order(name: :asc)
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(whitelist_params)
    if @category.save
      flash[:notice] = "Category #{@category.name} successfully created"
      redirect_to categories_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @category.update(whitelist_params)
      #  Use flash helper to display feedback message
      flash[:notice] = 'Category successfully updated'
      redirect_to categories_path
    else
      # The update of the category has failed, so:
      # 1:  re-render the new form on which we loop through the
      #     error messages associated with the attempt to save the category
      # 2:  NOTE:  ", status: :unprocessable_entity" is needed by turbo_streams
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    if @category.delete
      #  Use flash helper to display feedback message
      flash[:notice] = "Category #{@category.name} successfully deleted"
      redirect_to categories_path
    else
      # The deletion of the category has failed, so:
      # 1:  re-render the show form on which we loop through the
      #     error messages
      # 2:  NOTE:  ", status: :unprocessable_entity" is needed by turbo_streams
      render 'show', status: :unprocessable_entity
    end
  end

  private

  def whitelist_params
    params.require(:category).permit(:name)
  end

  def require_admin_user
    if logged_in? && current_user.admin
      true
    else
      flash[:warning] = 'You must be an admin user to alter categories'
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name,
            category_path(category),
            class: "badge rounded-pill mybadge-background mybadge-text" %>



app/views/categories/_category_list.html.erb
<div class="container text-center">
  <div class="row row-cols-5">
    <% @categories.each do |category| %>
      <div class="col mt-2">
        <div class="card">
          <div class="card-text">
            <%= link_to category.name, category_path(category),
                                       class: 'link-dark text-decoration-none' %>
          </div>
          <% if category.articles.count > 0 %>
            <div class="card-text text-muted">
              <%= pluralize(category.articles.count, 'article') %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="container justify-content-center col-6">

  <%= form_with(model: @category, local: true, class: "shadow p-3 mb-3 bg-grey rounded") do |f| %>

    <div class="form-group row">

        <%= f.label 'Name:', class: 'col-2 col-form-label' %>

        <div class="col-10">
          <%= f.text_field :name,
                            autofocus: true,
                            class: 'form-control shadow rounded',
                            placeholder: "Enter a category" %>
        </div>

    </div>

    <div class="text-center mt-2">
        <%= f.submit %>
    </div>

  <% end %>

</div>

<div class="text-center mt-2 mb-2">
  <%= link_to '[ Cancel and return to Articles Listing ]',
              articles_path,
              class: 'text-decoration-none' %>
</div>

app/views/categories/edit.html.erb
<h4 class="row justify-content-center mt-2">Edit Article Category</h4>

<%= render 'shared/errors', obj: @category %>
<%= render 'form' %>

app/views/categories/index.html.erb
<h2 class="text-center mt-2">Categories</h2>

<!--Utilizing the will_paginate gem to include pagination in the rendering of the listing -->
<div class="apple_pagination">
  <%= will_paginate @categories, container: false %>
</div>

<%= render 'categories/category_list' %>

<div class="apple_pagination">
  <%= will_paginate @categories, container: false %>
</div>


app/views/categories/new.html.erb
<h4 class="row justify-content-center mt-2">Create an Article Category</h4>

<%= render 'shared/errors', obj: @category %>
<%= render 'form' %>



app/views/categories/show.html.erb
<h4 class="row justify-content-center mt-2">Category: <%= @category.name %> </h4>
<% if logged_in? and current_user.admin %>
  <div class="row justify-content-md-center">
    <div class="col-1">
      <%= link_to "Edit", edit_category_path(@category), class: "btn btn-outline-primary" %>
    </div>
    <div class="col-1">
      <%= button_to "Delete", @category,
                    class: "btn btn-outline-danger",
                    method: :delete,
                    onclick: "return confirm('Are you sure?')" %>
    </div>
  </div>
<% end %>

<% if @category.articles.count > 0 %>
  <h5 class="row justify-content-center">Articles:</h5>
  <div class="container">
    <div class="row justify-content-center">

      <% @category.articles.each do |article| %>
        <div class="accordion col-10" id="accordion<%= article.id %>">
          <div class="accordion-item">

            <h2 class="accordion-header">
              <button class="accordion-button"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapse<%= article.id %>"
                      aria-expanded="true"
                      aria-controls="collapse<%= article.id %>">

                  <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                      <strong><%= "#{article.title.titleize}"%></strong>
                      by <%="#{article.user.username.titleize}" %>
                    </li>
                  </ul>
              </button>
            </h2>

            <div id="collapse<%= article.id %>"
                class="accordion-collapse collapse">
              <div class="accordion-body">
                <%= article.description %>
              </div>
            </div>

          </div>
        </div>
      <% end %>

    </div>
  </div>
<% else %>
  <h5 class="row justify-content-center mt-2">There are no articles in this category </h5>
<% end %>

