config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles
  # get 'articles', to: 'articles#index'
  # get 'articles/:id', to: 'articles#show'

  # Routes for User actions
  get 'signup', to: 'users#new'

  # The form_with statement in users/_form.html.erb needs to know where to post
  # the form.  Since we pass it model: @user, it looks for users_path.
  # Since the form is invoked by the "new" method we complete the new user creation
  # by sending the form's data to the create method:
  # post 'users', to: 'users#create'
  # Alternatively, the resources statement assigns all the standard routes.  But we
  # want the "new" method to be invoked by signup [as above] so we can omit it from the
  # resources statement
  resources :users, except: [:new]

  # Routes for Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  # Tried "delete 'Logout', to 'sessions#destry" but that didn't work
  get 'logout', to: 'sessions#destroy'

  #  Routes for Categories
  resources :categories
end

app/views/layouts/_footer.html.erb
<footer class="mt-auto sticky-bottom border-top">
  <div class="container">
    <span class="text-muted">©<i>Someguy S/W Productions</i></span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div id="page-backer">
  <div class="container col-6">
    <% flash.each do |msg_type, msg| %>

      <% if msg_type == 'notice' %>
        <% message_display_type = 'alert-success' %>
      <% elsif msg_type == 'warning' %>
        <% message_display_type = 'alert-warning' %>
      <% else %>
        <% message_display_type = 'alert-secondary' %>
      <% end %>

      <div class="alert <%= message_display_type %> alert-dismissible fade show" role="alert">

        &#9757; <%= msg %>

        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>

    <!--This button is the hamburger button that navbar functions collapse into on small screens -->
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            Bloggers
          </a>
          <ul class="dropdown-menu">
            <% if !logged_in? %>
              <li> <%= link_to "Sign Up!", signup_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Log In", login_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
            <% end %>
            <li><%= link_to "Our Bloggers", users_path, class: "dropdown-item" %></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Articles Listing", articles_path, class: "dropdown-item" %></li>
            <li><%= link_to "Article Categories", categories_path, class: "dropdown-item" %></li>
          </ul>
        </li>

        <% if logged_in? && current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin:)  " if current_user.admin%> <%= current_user.username.titleize %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Articles", user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "New Article", new_article_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Edit My Profile",
                              edit_user_path(current_user),
                              class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Log Out", logout_path,
                              class: "dropdown-item",
                              data: { "turbo-method": :delete } %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Create a Category",
                              new_category_path,
                              class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to "Delete Account",
                                user_path(current_user),
                                class: "dropdown-item text-danger",
                                method: :delete,
                                onclick: "return confirm('Are you sure?')" %></li>
            </ul>
        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">

        <li class="nav-item ml-auto">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>

      </ul>

    </div>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">

    <%= render 'layouts/navbar' %>

    <div id=page-background>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>


  </body>
</html>